### ISSUE TITLE
Project needs a logo

### ISSUE THREAD

**Issue by forki** [fsprojects/Canopy.Mobile#1]
/cc @sergey-tihon ;-)

**Comment by sergey-tihon** [comment]
We will think about it =)
I think that it should be similar to canopy logo:

![image](https://cloud.githubusercontent.com/assets/1197905/21344592/92632060-c6ad-11e6-87a1-59e0b7ceabeb.png)

**Comment by forki** [comment]
yes. something that uses the canopy logo and adds a mobile phone or something

**Comment by sergey-tihon** [comment]
![image](https://cloud.githubusercontent.com/assets/1197905/21367285/9aa91606-c70e-11e6-8384-b8e9a7f08f3c.png)
FsAdvent edition =)

**Comment by forki** [comment]
I like it a lot. @lefthandedgoat what do you think? I mean it's even the left hand.

**Comment by forki** [comment]
@sergey_tihon could you please send it as pull request?

**Comment by sergey-tihon** [comment]
sure, but I have one more version
![image](https://cloud.githubusercontent.com/assets/1197905/21420294/fac15aaa-c83d-11e6-8f75-37f1acfb6770.png)

@forki which one do you like?

**Comment by forki** [comment]
the last one is probably better to see in small res
