### ISSUE TITLE
Fight flakiness

### ISSUE THREAD

**Issue by forki** [fsprojects/Canopy.Mobile#15]
Currently this testsuite still fails on our internal gitlab for timing issues. I assume we need to wait until the app is uploaded after every test. @lefthandedgoat us this possible?

**Comment by lefthandedgoat** [comment]
I suspect it is, but I need to get it so I can launch the emulator from the code locally so I can try stuff out.  Still stuck on that one.

**Comment by forki** [comment]
what is the concrete error when you run build.cmd?

**Comment by forki** [comment]
ok seems I found the issue for the flakiness in build. If the emulator is started with -no-window (headless mode) then android back button doesn't work

**Comment by forki** [comment]
http://stackoverflow.com/questions/41363912/press-android-back-button-with-appium-in-no-window-mode

**Comment by forki** [comment]
unfortunately this confused the build server and it's now hanging forever.

**Comment by forki** [comment]
let's see if 77cd0b72e81b510c76ab81654faac90c949d6322 helps with the hanging processes

**Comment by forki** [comment]
Ok it seems the hanging problem is fixed, but unfortunately I get "GL error while resizing" on the CI an the back button is still not working. It definetly is working on my laptop in non-headless mode.
So the question is: what is happening on the CI?

**Comment by forki** [comment]
seems the error is related to screen resolution: http://stackoverflow.com/questions/39574264/android-gl-error-while-resizing-0x506-ignored

**Comment by forki** [comment]
Ok. the back button is available in headless mode. Everything was a timing issue and is now resolved. I will add some helpers for animations to make that easier

**Comment by lefthandedgoat** [comment]
What resolution is the build machine?  If its running the worker agent as a windows services then I believe it is only 1024x768 and you have to change your setup to get it to work at a higher resolution.

You have to have the agent run from a DOS window on startup (if the CI server you are using has that option, which allows the resolution to be higher.

Instructions for TeamCity:
https://gist.github.com/lefthandedgoat/9138759

**Comment by forki** [comment]
resolution issue was fixed since we go headless again ;-)
