### ISSUE TITLE
Propose misspelled selectors if a selection fails

### ISSUE THREAD

**Issue by forki** [fsprojects/Canopy.Mobile#19]
@lefthandedgoat can you please port the canopy code around levensthein? Thx

**Comment by lefthandedgoat** [comment]
I can do it I just need to figure out how to grab all of the existing elements so I can give suggestions.  Will take some work.

**Comment by forki** [comment]
something like XPath //* might work?

2016-12-29 18:10 GMT+01:00 Chris Holt <notifications@github.com>:

**Comment by lefthandedgoat** [comment]
Yep, but if we provide syntactic sugar for things like ID I will need to make it give good suggestions there too.

**Comment by lefthandedgoat** [comment]
I haven't forgotten about this and I will work on it today.
