### ISSUE TITLE
Design discussion:  Create own test runner or use existing like xUnit/fsUnit/etc

### ISSUE THREAD

**Issue by lefthandedgoat** [fsprojects/Canopy.Mobile#3]
Creating a console based test runner is actually pretty easy and I have 2 working examples, one in canopy, and a parallel enabled one called prunner.

They offer a lot of pros but offer some cons.

##Pros
Simple and easy to make
Console is actually really powerful and well supported in various CI environments

##Cons (all of these do not bother me but frequently come up in issues on canopy)
No VS integration
People generally aren't as familiar with how to use console
You have to roll your own 'tags' for tests so that you can run subsets etc
Not xUnit/nUnit/the testing library they are used to

**Comment by forki** [comment]
Currentlying I'm going with expecto

**Comment by adalenthya** [comment]
Do you think it's possible to use Canopy.Mobile with Nunit, instead of expecto? 
I'm already running Canopy for desktop tests with Nunit, and would prefer to use the same.

**Comment by forki** [comment]
You should consider to change the canopy to expecto as well. Seriously.

But that said: is should already be possible to use Canopy.Mobile with
nunit.

Am 15.11.2017 10:34 schrieb "adalenthya" <notifications@github.com>:
