### ISSUE TITLE
Design discussion:  Parallel test run support

### ISSUE THREAD

**Issue by lefthandedgoat** [fsprojects/Canopy.Mobile#5]
canopy can only run tests in one browser at a time because it uses a global mutable instance of the browser.  It makes the api really nice but more advanced users want to run more than one test at the same time.

The easiest way for them to do this is to simply parameterize their console app to run a subset of tests, or with different browsers, and run the console app more than one time.

Some people (not many) want true parallel support in the same process.  This is not hard to do, as you can add an instance of the browser/simulator as a parameter to ALL function calls, but obviously this makes the api kind of unpleasant.

You can support 2 apis, one that is nice and clean, and one that is less clean but allows for parallel.

This may not be a big problem for android/ios though because starting the simulator is so expensive.

**Comment by forki** [comment]
I don't know if we can really benefit from parallel tests. If people want
that, then let them parallelize in outer fake script.

Am 17.12.2016 6:26 nachm. schrieb "Chris Holt" <notifications@github.com>:
