### ISSUE TITLE
Stuck trying to run build.cmd

### ISSUE THREAD

**Issue by lefthandedgoat** [fsprojects/Canopy.Mobile#6]
https://github.com/fsprojects/Canopy.Mobile/commit/259fa0d86b9b1a3fa8ebd025c821f144bda6716b#diff-6074983490330a0aac1bd23c958232d7R89

You switched from "sdk" to "android-sdk".  I had a sdk folder but not android-sdk folder.  It does not work with just sdk either.

I installed with the latest Android Studio package.  Is there something else I need to install?  I also created a hello world app, and installed API 23 (Marshmellow I think) and created an emulate for Nexus 6 because it seemed to be breaking on Nexus_6_23 and it launches from the IDE, and I get beyond that error now.

Here is the trace of where it is failing when I modify the path back to sdk fyi:

```
Finished Target: InstallAppium
Starting Target: RunTests (==> InstallAppium)
C:\projects\Canopy.Mobile\tests\Canopy.Mobile.Tests\bin\Release\Canopy.Mobile.Tests.exe --sequential
app C:\projects\Canopy.Mobile\tests\Canopy.Mobile.Tests\bin\Release\temp\ApiDemos-debug.apk already exists
Error: Environment variable HOME is not set.

Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at canopy.mobile.core.quit() in C:\projects\Canopy.Mobile\src\Canopy.Mobile\Canopy.Mobile.fs:line 93
   at Canopy.Mobile.Tests.main(String[] args) in C:\projects\Canopy.Mobile\tests\Canopy.Mobile.Tests\SampleTests.fs:line 127
```

**Comment by forki** [comment]
I removed the check for HOME env variable and added a check if ANDROID_HOME is already set from the outside

**Comment by lefthandedgoat** [comment]
I am still having problems.  I reinstalled the android tools to use the android-sdk folders that you are looking for.

I created a new Simulator called "AVD for Nexus 6 by Google"

![image](https://cloud.githubusercontent.com/assets/725225/21408214/5ec76fb2-c799-11e6-82cb-0eb2b9bfe41b.png)

Not sure what I am doing wrong. Appium does not want to launch the Simulator.  Any ideas?

This is the error I get: 

```
Finished Target: InstallAppium
Starting Target: RunTests (==> InstallAppium)
C:\projects\Canopy.Mobile\tests\Canopy.Mobile.Tests\bin\Release\Canopy.Mobile.Tests.exe --sequential
app C:\projects\Canopy.Mobile\tests\Canopy.Mobile.Tests\bin\Release\temp\ApiDemos-debug.apk already exists
Error: An unknown server-side error occurred while processing the command. Original error: Avd 'AVD_for_Nexus_6_by_Google' is not available. please select your avd name from one of these: '()'

Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at canopy.mobile.core.quit() in C:\projects\Canopy.Mobile\src\Canopy.Mobile\Canopy.Mobile.fs:line 89
   at Canopy.Mobile.Tests.main(String[] args) in C:\projects\Canopy.Mobile\tests\Canopy.Mobile.Tests\SampleTests.fs:line 127
```

**Comment by forki** [comment]
Ok it looks like path information is still wrong. I was having the very same problem and had to play with Android home path in Windows for a while. It seems I have multiple Android sdks installed and only one is working correctly with appium. Even after that I had to recreate the emulator image. It's a mess. 

In our real app I tried to start the emulator directly via command line call and appium is using the running emulator. This seems to be more robust. I will build this into Canopy.mobile and hopefully this will fix it for you.

**Comment by part-timeDev** [comment]
could you please verify that your avd is located in one of the following paths

$ANDROID_AVD_HOME
$ANDROID_SDK_HOME\.android\avd
$HOME\.android\avd

or set one of the above to the vaild path of your avd

**Comment by forki** [comment]
see https://github.com/fsprojects/Canopy.Mobile/pull/7

**Comment by forki** [comment]
Ok we changed the way we start the emulator and don't trust appium for that anymore.

**Comment by lefthandedgoat** [comment]
I am all cleared up.
